spring.application.name=booking-service

# Database connection (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=booking_service;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate (let it create/update tables; LocalDateTime -> DATETIME2)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
